// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXCIDvuZRFTN-H5CkPxkBvZlZU8cAiNI',
    appId: '1:131175468738:web:a180decdebaca3eabfb55b',
    messagingSenderId: '131175468738',
    projectId: 'ast-app-80205',
    authDomain: 'ast-app-80205.firebaseapp.com',
    storageBucket: 'ast-app-80205.firebasestorage.app',
    measurementId: 'G-TT9R665V1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtTGTeRHZPPxPLqIgtNh_ptgNXMqpSHF0',
    appId: '1:131175468738:android:399a5759f7163bc9bfb55b',
    messagingSenderId: '131175468738',
    projectId: 'ast-app-80205',
    storageBucket: 'ast-app-80205.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLzHAfq4WcIdVy0FGfabnOpn9xR4rq1E',
    appId: '1:131175468738:ios:26f74f7efd39b31fbfb55b',
    messagingSenderId: '131175468738',
    projectId: 'ast-app-80205',
    storageBucket: 'ast-app-80205.firebasestorage.app',
    iosBundleId: 'com.example.astOfficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwLzHAfq4WcIdVy0FGfabnOpn9xR4rq1E',
    appId: '1:131175468738:ios:26f74f7efd39b31fbfb55b',
    messagingSenderId: '131175468738',
    projectId: 'ast-app-80205',
    storageBucket: 'ast-app-80205.firebasestorage.app',
    iosBundleId: 'com.example.astOfficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXXCIDvuZRFTN-H5CkPxkBvZlZU8cAiNI',
    appId: '1:131175468738:web:d39fa23bbe456aacbfb55b',
    messagingSenderId: '131175468738',
    projectId: 'ast-app-80205',
    authDomain: 'ast-app-80205.firebaseapp.com',
    storageBucket: 'ast-app-80205.firebasestorage.app',
    measurementId: 'G-QDTDP4NE5K',
  );
}
